[package]
name = "bpf-program-template"
version = "0.1.0"
edition = "2018"
license = "WTFPL"

[dependencies]
solana-program = "1.4.4"

[dev-dependencies]
assert_matches = "1.4.0"
solana-program-test = "1.4.4"
solana-sdk = "1.4.4"
tokio = { version = "0.3", features = ["macros"]}

[lib]
crate-type = ["cdylib"]

[workspace]
